sudo: true

language: android
dist: precise
# Ant is required in order to compile buck.
install: ant deps
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26

before_install:
  - export SKIP_OKBUCK=true
  - export EXTRA_OKBUCK_ARGS="--quiet --stacktrace"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager).
  - sdkmanager tools
  # Install the system image.
  - sdkmanager "system-images;android-19;default;armeabi-v7a"
  - echo no | avdmanager create avd -f -n test -k "system-images;android-19;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install:
  - echo "Override default Travis install step to avoid unnecessary './gradlew assemble'."

script:
  - SKIP_OKBUCK= ./buckw --version
  - ./buckw targets --type android_binary android_instrumentation_apk java_test groovy_test robolectric_test kotlin_test scala_test | xargs ./buckw build -v 0
  - ./buckw targets --type genrule | grep -v lintErrorLibrary | xargs ./buckw build -v 0
  - ./buckw build //libraries/lintErrorLibrary:lint_debug -v 0;
    if [ $? -eq 0 ]; then
      echo "Lint passed when it should have failed. Please revisit any changes you may have made to lint wiring.";
      exit 1;
    else
      if grep -q 'id=\"DontUseSystemTime\"' 'buck-out/gen/libraries/lintErrorLibrary/lint_debug/lint_debug_out/lint-results.xml'; then
        echo "Lint failed as expected.";
      else
        echo "Lint did not create the expected output. Please double check your changes to resolve.";
        exit 1;
      fi
    fi
  - ./buckw test --include unit
  - android-wait-for-emulator
  - adb shell input keyevent 82
  - ./buckw test //app:instrumentation_demoDebug_test

after_failure:
  - find * -name lint-results.xml | xargs cat
  - adb -e logcat -d '*:E';
  - echo "get the full logcat here:";
  - adb -e logcat -d | curl --silent -F 'clbin=<-' https://clbin.com;

notifications:
  email: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - buck-out/cache
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/
